import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PDFDocument} from 'pdf-lib';
import {draftElements,removeDuplicateDraftText} from '../lib/image-draft';
import {draftPayload,draftSchema,imageRequest} from '../lib/image-draft-schema';
import {fitDraftText} from '../lib/draft-text-fit';
import {scenePdf,sceneFromPdf,MM,type Scene} from '../lib/design-scene';

globalThis.fetch=async(input:any)=>new Response(fs.readFileSync('public'+String(input)));
const spec={faceWidth:210,faceHeight:297,bleed:0,sourceIncludesBleed:true,product:'letter' as const,productConfirmed:true,bleedConfirmed:true,sizeConfirmed:true,marks:false};
const base={kind:'text' as const,label:'Address',x:.04,y:.56,w:.55,h:.034,text:'30 Mamie Avenue Seven Hills',font:'sans' as const,bold:true,italic:false,fontHeight:.031,color:'#ffffff',align:'left' as const,shape:'rectangle' as const,lineHeight:1.15};
const draft=draftSchema.parse({background:'#ffffff',notes:[],elements:[base,{...base,label:'Letter body',x:.1,y:.33,w:.8,h:.19,text:'We are delighted to inform you that we have just listed another property\nin your neighbourhood. My team at Stone have been chosen as the\nselling agents for 1/49 Woodbury Park Drive, Mardi. During the\nmarketing campaign of this property, you may notice a little more\nactivity in the street than usual.',bold:false,fontHeight:.02,lineHeight:1.8},{...base,label:'Footer email',x:.05,y:.96,w:.18,h:.018,text:'tumbiumbi@stonerealestate.com.au',fontHeight:.018,color:'#000000'}]});
const elements=draftElements(draft,spec,210/297);
assert.ok(Math.abs(elements[0].y-.56*297)<1e-9,'vertical coordinates use page height');
assert.equal(elements[1].lineHeight,1.8);
const duplicate={...elements[1],id:'duplicate-address',label:'Address',text:'1/49 Woodbury Park Drive, Mardi.',y:elements[1].y+5,h:4};
assert.equal(removeDuplicateDraftText([...elements,duplicate]).length,elements.length,'inline address is not duplicated over the paragraph');
await fitDraftText(elements);
assert.ok(elements[0].size<base.fontHeight*297*MM,'oversized source estimate is fitted');
const scene:Scene={version:1,name:'Scan reconstruction regression',spec,pages:[{background:'#ffffff',elements}]};
const bytes=await scenePdf(scene);
const pdf=await PDFDocument.load(bytes),page=pdf.getPage(0);
assert.ok(Math.abs(page.getWidth()/MM-210)<.001);
assert.ok(Math.abs(page.getHeight()/MM-297)<.001);
assert.deepEqual(page.getTrimBox(),page.getBleedBox());
assert.deepEqual(await sceneFromPdf(bytes),scene,'editable content and line breaks survive PDF roundtrip');
const payload=draftPayload('data:image/jpeg;base64,AAAA','gpt-5.4',1448,2048);
const imageContent=(payload.input[1].content as {detail?:string}[])[1];
assert.equal(imageContent.detail,'original');
assert.ok(imageRequest.safeParse({image:'data:image/jpeg;base64,AAAA',width:1448,height:2048}).success);
fs.mkdirSync('work',{recursive:true});fs.writeFileSync('work/scan-fit-regression.pdf',bytes);
console.log('PASS: measured text fitting, explicit line spacing, original-dimension mapping, editable roundtrip, A4 zero bleed, original-detail analysis request');
