import {env} from 'cloudflare:workers';
import {checkOrigin,user,failure} from '@/lib/template-storage';
import {imageRequest,draftPayload,parseDraftResponse} from '@/lib/image-draft-schema';
const active=new Set<string>();
export async function GET(){return Response.json({available:!!(env as any).OPENAI_API_KEY},{headers:{'Cache-Control':'no-store'}})}
export async function POST(request:Request){let owner='',acquired=false;try{checkOrigin(request);owner=user(request);const key=(env as any).OPENAI_API_KEY;if(!key)return Response.json({error:'Image analysis is not connected yet. The Studio owner needs to enable it.'},{status:503});if(active.has(owner))return Response.json({error:'An image is already being analysed. Please wait.'},{status:429});if(Number(request.headers.get('content-length'))>6100000)return Response.json({error:'Image is too large. Choose a smaller image.'},{status:413});
 const reader=request.body?.getReader();if(!reader)return Response.json({error:'Choose an image.'},{status:400});let text='',count=0;const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;count+=value.length;if(count>6100000){await reader.cancel();return Response.json({error:'Image is too large.'},{status:413})}text+=decoder.decode(value,{stream:true})}text+=decoder.decode();const input=imageRequest.safeParse(JSON.parse(text));if(!input.success)return Response.json({error:'Choose a JPG or PNG image.'},{status:400});active.add(owner);acquired=true;
 const result=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(draftPayload(input.data.image,(env as any).OPENAI_VISION_MODEL||'gpt-5.4',input.data.width,input.data.height)),signal:AbortSignal.timeout(230000)});if(!result.ok)return Response.json({error:result.status===429?'Image analysis is busy or its credit limit has been reached. Try again later.':'Image analysis could not finish. Try again or contact the Studio owner.'},{status:502});let draft;try{draft=parseDraftResponse(await result.json())}catch(e){return Response.json({error:e instanceof SyntaxError?'The analysis returned an unreadable response. Please retry.':e instanceof Error?e.message:'The analysis did not return a usable layout. Please retry.'},{status:502})}return Response.json(draft,{headers:{'Cache-Control':'no-store'}});
 }catch(e){if((e as any)?.status)return failure(e);return failure(new Error(e instanceof SyntaxError?'The image request could not be read.':e instanceof Error&&e.name==='TimeoutError'?'Image analysis timed out. Try a simpler image.':'The analysis service could not complete the request. Please retry. Your uploaded file is still available.'),422)}finally{if(acquired)active.delete(owner)}}
