import { useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, ChevronRight, Circle, FileImage, ImageIcon, Layers3, LoaderCircle, Minus, MousePointer2, Sparkles, Square, Trash2, Type, Upload } from "lucide-react";
import { trpc } from "@/lib/trpc";

type ElementKind = "text" | "image" | "rectangle" | "ellipse" | "line";
type DesignElement = { kind: ElementKind; label: string; x: number; y: number; w: number; h: number; text: string; font: "sans" | "serif"; bold: boolean; italic: boolean; fontHeight: number; color: string; align: "left" | "center" | "right"; shape: "rectangle" | "square" | "circle" | "oval" | "rounded" };
type Draft = { background: string; notes: string[]; elements: DesignElement[]; model?: string };

const emptyElement = (kind: ElementKind): DesignElement => ({ kind, label: kind === "text" ? "New text" : kind === "image" ? "Image" : "Shape", x: 0.12, y: 0.12, w: kind === "line" ? 0.32 : 0.26, h: kind === "line" ? 0.008 : 0.12, text: kind === "text" ? "New text" : "", font: "sans", bold: kind === "text", italic: false, fontHeight: kind === "text" ? 0.055 : 0, color: kind === "line" ? "#101828" : "#ffffff", align: "left", shape: kind === "ellipse" ? "circle" : "rectangle" });
function kindIcon(kind: ElementKind) { const props = { size: 15, strokeWidth: 1.8 }; if (kind === "text") return <Type {...props} />; if (kind === "image") return <ImageIcon {...props} />; if (kind === "ellipse") return <Circle {...props} />; if (kind === "line") return <Minus {...props} />; return <Square {...props} />; }
function clamp(value: number, fallback: number) { return Number.isFinite(value) ? Math.min(1, Math.max(0, value)) : fallback; }

export default function Home() {
  const picker = useRef<HTMLInputElement>(null);
  const [reference, setReference] = useState("");
  const [fileName, setFileName] = useState("");
  const [draft, setDraft] = useState<Draft | null>(null);
  const [selected, setSelected] = useState<number | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const status = trpc.designDraft.status.useQuery();
  const createDraft = trpc.designDraft.create.useMutation({
    onSuccess: (result) => { setDraft(result); setSelected(Math.max(0, result.elements.findIndex((element) => element.kind === "text"))); setNotice("Editable draft ready. Review every element before using it in production."); setError(""); },
    onError: (reason) => setError(reason.message),
  });
  const activeElement = selected !== null && draft ? draft.elements[selected] : null;
  const available = status.data?.available === true;
  const canvasStyle = useMemo(() => ({ backgroundColor: draft?.background || "#f8fafc" }), [draft?.background]);
  function updateElement(patch: Partial<DesignElement>) { if (!draft || selected === null) return; setDraft({ ...draft, elements: draft.elements.map((element, index) => index === selected ? { ...element, ...patch } : element) }); }
  async function chooseFile(file?: File) { if (!file) return; setError(""); setNotice(""); setDraft(null); setSelected(null); if (!/(image\/jpeg|image\/png)/.test(file.type)) { setError("Choose a JPG or PNG reference image."); return; } if (file.size > 4 * 1024 * 1024) { setError("Choose an image below 4 MB for a faster, more reliable draft."); return; } const reader = new FileReader(); reader.onerror = () => setError("The image could not be read. Please try another file."); reader.onload = () => { setReference(String(reader.result)); setFileName(file.name); setNotice("Reference loaded. Choose Create editable draft when you are ready."); }; reader.readAsDataURL(file); }
  function addElement(kind: ElementKind) { const next = emptyElement(kind); if (!draft) { setDraft({ background: "#ffffff", notes: ["Manually added element — add a reference image to use AI recognition."], elements: [next] }); setSelected(0); return; } const nextDraft = { ...draft, elements: [...draft.elements, next] }; setDraft(nextDraft); setSelected(nextDraft.elements.length - 1); }
  function removeSelected() { if (!draft || selected === null) return; const next = draft.elements.filter((_, index) => index !== selected); setDraft({ ...draft, elements: next }); setSelected(next.length ? Math.min(selected, next.length - 1) : null); }
  return <div className="studio-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="Signboard Studio home"><span className="brand-mark"><Layers3 size={20} /></span><span>Signboard <strong>Studio</strong></span></a><div className="header-status"><span className={`status-dot ${available ? "ready" : ""}`} />{status.isLoading ? "Checking AI" : available ? "AI recognition connected" : "AI unavailable"}</div></header>
    <main className="studio-main">
      <section className="hero-copy"><span className="eyebrow"><Sparkles size={14} /> AI-assisted drafting</span><h1>Turn a reference design into an editable starting point.</h1><p>Upload a signboard, flyer or social export. The studio maps visible text, images and shapes into editable layers without exposing an API key in your browser.</p></section>
      <div className="workspace">
        <aside className="left-panel"><section className="panel-card upload-card"><div className="card-heading"><span className="step-number">01</span><div><h2>Reference image</h2><p>JPG or PNG, up to 4 MB</p></div></div><input ref={picker} className="sr-only" type="file" accept="image/jpeg,image/png" onChange={(event) => void chooseFile(event.target.files?.[0])} /><button className={`drop-zone ${reference ? "has-reference" : ""}`} onClick={() => picker.current?.click()} type="button">{reference ? <img src={reference} alt="Selected reference" /> : <><Upload size={25} /><span>Choose reference image</span><small>or drop it here</small></>}</button>{fileName && <div className="file-row"><FileImage size={16} /><span>{fileName}</span><button type="button" onClick={() => picker.current?.click()}>Replace</button></div>}<button className="primary-action" type="button" disabled={!reference || createDraft.isPending || !available} onClick={() => { if (reference) { setError(""); setNotice(""); createDraft.mutate({ image: reference }); } }}>{createDraft.isPending ? <><LoaderCircle className="spin" size={17} /> Reading the layout…</> : <><Sparkles size={17} /> Create editable draft</>}</button><p className="security-note"><CheckCircle2 size={15} /> Processed only by the server. Your browser never receives the AI credential.</p></section><section className="panel-card quick-add"><div className="card-heading"><span className="step-number">02</span><div><h2>Build manually</h2><p>Add or refine the draft</p></div></div><div className="tool-grid"><button type="button" onClick={() => addElement("text")}>{kindIcon("text")} Text</button><button type="button" onClick={() => addElement("image")}>{kindIcon("image")} Image</button><button type="button" onClick={() => addElement("rectangle")}>{kindIcon("rectangle")} Block</button><button type="button" onClick={() => addElement("ellipse")}>{kindIcon("ellipse")} Circle</button></div></section></aside>
        <section className="canvas-panel"><div className="canvas-toolbar"><div><span className="eyebrow muted">Editable draft</span><h2>{draft ? `${draft.elements.length} recognised layers` : "Your design workspace"}</h2></div><div className="toolbar-tip"><MousePointer2 size={15} /> Select a layer to edit</div></div><div className="canvas-scroll"><div className="design-canvas" style={canvasStyle}>{draft?.elements.map((element, index) => { const isSelected = index === selected; const borderRadius = element.shape === "circle" || element.shape === "oval" || element.kind === "ellipse" ? "999px" : element.shape === "rounded" ? "14px" : "0"; const imageStyle = element.kind === "image" && reference ? { backgroundImage: `url(${reference})` } : undefined; return <button type="button" key={`${element.label}-${index}`} className={`design-element ${element.kind} ${isSelected ? "selected" : ""}`} onClick={() => setSelected(index)} style={{ left: `${clamp(element.x, 0) * 100}%`, top: `${clamp(element.y, 0) * 100}%`, width: `${Math.min(1 - clamp(element.x, 0), Math.max(.015, element.w)) * 100}%`, height: `${Math.min(1 - clamp(element.y, 0), Math.max(.008, element.h)) * 100}%`, color: element.color, textAlign: element.align, fontFamily: element.font === "serif" ? "Georgia, serif" : "Inter, sans-serif", fontWeight: element.bold ? 800 : 500, fontStyle: element.italic ? "italic" : "normal", fontSize: `${Math.max(9, element.fontHeight * 520)}px`, borderRadius, ...imageStyle }}>{element.kind === "text" ? <span>{element.text || "Text"}</span> : element.kind === "image" ? <span className="image-layer-label"><ImageIcon size={14} /> {element.label}</span> : <span className="shape-layer-label">{isSelected && element.label}</span>}</button>; })}{!draft && <div className="canvas-empty"><span><Sparkles size={24} /></span><h3>Start with a reference</h3><p>Upload an image to have AI construct a first-pass layer map, or add elements manually.</p></div>}</div></div>{notice && <div className="notice success"><CheckCircle2 size={17} /> {notice}</div>}{error && <div className="notice error"><AlertCircle size={17} /> {error}</div>}</section>
        <aside className="right-panel"><section className="panel-card layers-card"><div className="card-heading"><span className="step-number">03</span><div><h2>Layers</h2><p>{draft?.elements.length ? "Ordered back to front" : "No layers yet"}</p></div></div><div className="layers-list">{draft?.elements.map((element, index) => <button key={`${element.label}-list-${index}`} type="button" className={selected === index ? "layer-row active" : "layer-row"} onClick={() => setSelected(index)}>{kindIcon(element.kind)}<span>{element.label}</span><ChevronRight size={15} /></button>)}{!draft && <p className="empty-layers">Recognised layers will appear here.</p>}</div></section><section className="panel-card inspector-card"><div className="inspector-title"><div><h2>Inspector</h2><p>{activeElement ? `${activeElement.kind} layer` : "Select a layer"}</p></div>{activeElement && <button className="delete-button" type="button" aria-label="Delete selected layer" onClick={removeSelected}><Trash2 size={16} /></button>}</div>{activeElement ? <div className="inspector-fields"><label>Layer name<input value={activeElement.label} onChange={(event) => updateElement({ label: event.target.value.slice(0, 80) })} /></label>{activeElement.kind === "text" && <label>Text<textarea value={activeElement.text} onChange={(event) => updateElement({ text: event.target.value.slice(0, 6000) })} /></label>}<div className="field-pair"><label>X<input type="number" min="0" max="1" step="0.01" value={activeElement.x} onChange={(event) => updateElement({ x: clamp(Number(event.target.value), activeElement.x) })} /></label><label>Y<input type="number" min="0" max="1" step="0.01" value={activeElement.y} onChange={(event) => updateElement({ y: clamp(Number(event.target.value), activeElement.y) })} /></label></div><div className="field-pair"><label>Width<input type="number" min="0.01" max="1" step="0.01" value={activeElement.w} onChange={(event) => updateElement({ w: Math.min(1, Math.max(.01, Number(event.target.value))) })} /></label><label>Height<input type="number" min="0.01" max="1" step="0.01" value={activeElement.h} onChange={(event) => updateElement({ h: Math.min(1, Math.max(.01, Number(event.target.value))) })} /></label></div>{activeElement.kind !== "image" && <label>Colour<input type="color" value={activeElement.color} onChange={(event) => updateElement({ color: event.target.value })} /></label>}{activeElement.kind === "text" && <div className="toggle-row"><label><input type="checkbox" checked={activeElement.bold} onChange={(event) => updateElement({ bold: event.target.checked })} /> Bold</label><label><input type="checkbox" checked={activeElement.italic} onChange={(event) => updateElement({ italic: event.target.checked })} /> Italic</label></div>}</div> : <p className="inspector-empty">Choose a generated layer to change its text, size, position or styling.</p>}</section></aside>
      </div>
      {draft?.notes.length ? <section className="review-notes"><div><span className="eyebrow muted">AI review notes</span><h2>Check the draft before production</h2></div><ul>{draft.notes.map((note, index) => <li key={`${note}-${index}`}><AlertCircle size={15} /> {note}</li>)}</ul></section> : null}
    </main>
  </div>;
}
